<a href="https://colab.research.google.com/github/StillWork/lg1210/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC%EA%B8%B0%EB%B3%B8%EA%B8%B02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 처음 배우는 파이썬
- (1) 기본 변수: 정수, 소수, 불리언, 문자열
- (2) 집합 변수 : 리스트, 튜플, 딕셔너리

In [ ]:
x = 3 ; y = 0.5 ; b = True ; c = False
print(x+y+b+c)

4.5


In [ ]:
z = "Hello" ; z

'Hello'

- 리스트: 데이터를 담는 통

In [ ]:
x = [1,2,3,5,100] ; x.append(200) ; x

[1, 2, 3, 5, 100, 200]

In [ ]:
(a, b) = (8, 9) # 튜플
print(a)

8


In [ ]:
dic = {"a":5, "b":"아무 내용이나....."} # 딕셔너리
print(dic["a"])
dic["c"] = 1000 # 항목 추가
print(dic)
# ctrl + m + o

5
{'a': 5, 'b': '아무 내용이나.....', 'c': 1000}


[] - 리스트 만들때, 인덱싱  
() - 함수 호출 (append(..)), 튜플(데이터 묶음)  
{} - 딕셔너리 (키:값 으로 구성된 간단한 데이터베이스)  


In [ ]:
x

[1, 2, 3, 5, 100, 200]

In [ ]:
x[-2:]

[100, 200]

In [ ]:
# 코멘트 문장. 이것은 실행되지 않는 부분임, 슬라이싱 :  사용
x[1:4]

[2, 3, 5]

In [ ]:
x[3:]

[5, 100, 200]

In [ ]:
x[:4]

[1, 2, 3, 5]

흐름 관리 ":" 
- if, else, elif, 
- for
- while

In [ ]:
x = 13
if x > 10: 
  print("more than 10")
  print("more than 10 !!")
else:
  print("less that 10")

more than 10
more than 10 !!


In [ ]:
x = [1,2,5,10]
for i in x:
  print(i*10)

10
20
50
100


In [ ]:
tag = 0
while tag < 5 :
  print ('OK')
  tag = tag +1

OK
OK
OK
OK
OK


In [ ]:
x = [1,2,5,10] # 리스트 (조작용) 
print(x * 3)
type(x)

[1, 2, 5, 10, 1, 2, 5, 10, 1, 2, 5, 10]


list

In [ ]:
import numpy as np
y = np.array(x) # 리스트를 어레이로 전환 (계산을 위해서 배열로 바꿈)
print(y*3)
type(y)

[ 3  6 15 30]


numpy.ndarray

In [ ]:
z = list(y) ; z

[1, 2, 5, 10]

In [ ]:
x = [[1,2,3],
     [4,5,6]]  # 2차원 리스트
y = np.array(x) ; y*10  # 2차원 어레이 (계산용)

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
y + 1000

array([[1001, 1002, 1003],
       [1004, 1005, 1006]])

In [ ]:
import pandas as pd
df = pd.DataFrame(x) ; df # 데이터프레임을 생성 (액셀) 행번호(인덱스) 열(컬럼) 이름을 자동 생성

0  1  2
0  1  2  3
1  4  5  6

In [ ]:
df = pd.DataFrame(y, columns=["키", "몸무게", "나이"]) ; df

키  몸무게  나이
0  1    2   3
1  4    5   6

In [ ]:
df.values # 데이터프레임 --> 어레이 (인덱스와 컬럼명을 버리고 값만 취함)

array([[1, 2, 3],
       [4, 5, 6]])